language : node_js

addons:
    apt:
        packages:
            - rpm
            - xvfb

node_js:
    - 12.16

cache:
    directories:
        - node_modules

before_script:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm ci

script:
    - npm run package

after_success:
    - npm run coverage
