language : node_js

addons:
    apt:
        packages:
            - rpm
            - xvfb

node_js:
    - 12.20.1

cache:
    directories:
        - node_modules
        
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libusb-1.0-0-dev
  - sudo apt-get -y install libudev-dev

before_script:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm i

script:
    - npm run package
