export const REG_TX_GAS_CONSUMPTION = 10100;
export const REG_TX_GAS_CONSUMPTION_ATHENS = 10200;
export const REG_TX_GAS_CONSUMPTION_BABYLON = 10207;
export const EMPTY_OUT_TX_GAS_CONSUMPTION = 10260;
